config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :sequences, only: [:create, :parse, :preview, :perform_parse] do
    collection do
      get :parse
      get :preview
      post :post_data
      post :perform_parse
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/data_submit.rb
module DataSubmit
  SUBMIT_PATH = 'http://challenge.distribusion.com/the_one/routes'.freeze

  def post_data_to_server(data)
    HTTParty.post(SUBMIT_PATH, query: data, headers: { 'Content-Type' => 'application/json' })
    delete
  end

  def submit(pass)
    post_data_to_server(
      passphrase: pass,
      source: source,
      start_node: start_node,
      end_node: end_node,
      start_time: start_time[0...-1],
      end_time: end_time[0...-1]
    )
  end
end

app/models/concerns/files.rb
module Files
  def clean_working_directory
    FileUtils.rm_rf(Rails.root.join('tmp', 'downloads'))
  end

  def create_working_directory
    FileUtils.mkdir(Rails.root.join('tmp', 'downloads'))
  end
end

app/models/hint.rb
class Hint < ApplicationRecord
  extend Files
  include DataSubmit

  validates :source, presence: true
  validates :start_node, presence: true
  validates :end_node, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  enum source: [:sentinels, :sniffers, :loopholes]

  def self.download_sources
    self.clean_working_directory
    self.create_working_directory
    start_sequence = SourcesProcessorService.new
    start_sequence.download_files
    true
  end

  def self.parse_downloaded_data
    %w(SniffersParser SentinelsParser LoopholesParser).map do |parser|
      current_parser = parser.constantize.new
      current_parser.parse
      current_parser.parsed_objects.map do |item|
        Hint.create(item.to_h)
      end
    end
    self.clean_working_directory
    true
  end

  def self.send_all_data
    pass = Requestors::CredentialsRequestor.new.passphrase
    Hint.all.map { |hint| hint.submit(pass) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  def create
    if Hint.download_sources
      respond_to do |format|
        format.html { redirect_to parse_sequences_path }
      end
    end
  end

  def parse
    respond_to do |format|
      format.html
    end
  end

  def perform_parse
    if Hint.parse_downloaded_data
      respond_to do |format|
        format.html { redirect_to preview_sequences_path }
      end
    end
  end

  def preview
    @hints = Hint.all
    respond_to do |format|
      format.html
    end
  end

  def post_data
    if Hint.send_all_data
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matrix</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sequences/parse.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12 col-lg-12 col-md-12'>
      <div>Data Download Complete</div>
      <%= link_to 'Parse Downloaded Data', perform_parse_sequences_path, method: :post, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/sequences/preview.html.erb
<div class='container'>
  <div class='row top'>
    <div class='col-xs-12 col-lg-12 col-md-12'>
      <%= link_to 'Post parsed Data', post_data_sequences_path, method: :post, class: 'btn btn-success' %>
        <table class="table table-inverse">
          <thead>
            <tr>
              <th>source</th>
              <th>start_node</th>
              <th>end_node</th>
              <th>start_time</th>
              <th>end_time</th>
            </tr>
          </thead>
          <tbody>
            <% @hints.each do |hint| %>
              <tr>
                <th scope="row"><%= hint.source %></th>
                <td><%= hint.start_node %></td>
                <td><%= hint.end_node %></td>
                <td><%= hint.start_time[0...-1] %></td>
                <td><%= hint.end_time[0...-1] %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12 col-lg-12 col-md-12'>
      <%= link_to 'Initiate rescuing sequence', sequences_path, method: :post, class: 'btn btn-info' %>
    </div>
  </div>
</div>